### ISSUE TITLE
Make sure FormType::getName is SF3.0 compatible

### ISSUE THREAD

**Issue by Nyholm** [dmishh/SettingsBundle#73]

**Comment by rvanlaak** [comment]
I'm confused now I found out `framework-bundle` does not include the `form` component. See https://github.com/symfony/framework-bundle/blob/master/composer.json

So, apparently we do need to include the other components that were defined before: https://github.com/dmishh/SettingsBundle/blob/1.x/composer.json

The required components are defined via `require-dev` though, that's why tests pass: https://github.com/symfony/framework-bundle/blob/master/composer.json#L39

**Comment by Nyholm** [comment]
Oh, thats right. 
I do not think we need to add the components that is added by framework bundle. 

So :+1: to adding the form component to our composer.json

**Comment by rvanlaak** [comment]
What about the others?:

        "symfony/security": "~2.1,!=2.5.0",
        "symfony/validator": "~2.1,!=2.5.0",
        "symfony/translation": "~2.1,!=2.5.0",

**Comment by Nyholm** [comment]
We need to add 

```json
"symfony/form": "^2.7,^3.0",
"symfony/validator":  "^2.7,^3.0",
"symfony/translation":  "^2.7,^3.0",
```

Security is part of the framework bundle, right?

> Next to that, they should be "required" in Travis too.

Yes

**Comment by rvanlaak** [comment]
`translation` also is required via the `framework`.

**Comment by Nyholm** [comment]
Sorry, correct.

**Comment by rvanlaak** [comment]
`form` requires `validator`, see:  https://github.com/symfony/form/blob/master/composer.json#L28

See PR #74
