### ISSUE TITLE
Settings caching

### ISSUE THREAD

**Issue by dmishh** [dmishh/SettingsBundle#8]
Memcached, file system, etc

**Comment by Nyholm** [comment]
I'm happy to implement this one using DoctrineCacheBundle.

**Comment by dmishh** [comment]
Tobias, feel free to do this. Thanks!

**Comment by Nyholm** [comment]
The way I see it, there are two places you can implement a cache. I want to have a discussion what you (or anyone) think about these two (or a third) solution.

## Solution A)

Implement the cache before the SettingsManager layer. Every call to `SettingsManager::get` and `SettingsManager::all` will first check the cache and then the database. Calls to `SettingsManager::set`, `SettingsManager::setMany` and `SettingsManager::clear` will invalidate the cache. 

This solution is easy and strait forward. 

## Solution B)

Implement the cache in the SettingManager (logically). So every call to `SettingsManager::getSettingsFromRepository` and `SettingsManager::flush` will update the cache. 

This solution will generate fewer cache misses since we are fetching and caching all the user settings. 

``` php
// Request 1 (get 'alfa')
$this->get('settings_manager')->get('alfa', $this->getUser()); // cache miss

// Request 2 (get 'beta')
$this->get('settings_manager')->get('beta', $this->getUser()); // cache hit
```

This solution may cause more problem when users do not use the `SettingsManager::set` (which they should). This is also more aggressive and will take more cache storage. 

## Cache invalidation

If the developer updates the settings without the the SettingsManager we will suffer from invalid cache until the cache expires. There is no way around this, we just have to be clear with the documentation.

**Comment by dmishh** [comment]
I suggest that solution A is simpler and that's why I like it more. We can always switch to something more intelligent but keeping the complexity as low as possible is one of our goals. What do you think @Nyholm ?

**Comment by Nyholm** [comment]
Agreed!
